name: infra_repository

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  model: 
    path: ../model
  application: 
    path: ../application
  drift: 2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: 2.2.0+1
  build_runner: 2.3.0
  integration_test:
    sdk: flutter
  # build_test: 2.1.5
