name: application

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  model: 
    path: ../model
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

dev_dependencies:
  test: ^1.21.6
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
  build_test: any
  